import os
import re
import time
import smtplib
from email.message import EmailMessage

# SECURITY: Never hardcode real passwords. Use environment variables.
SENDER_EMAIL = os.getenv("SENDER_EMAIL")
APP_PASSWORD = os.getenv("APP_PASSWORD")


def _send_smtp(msg: EmailMessage, recipients: list[str]) -> None:
    """Internal helper to handle SMTP connection, login, and sending."""
    sender_email = SENDER_EMAIL or os.getenv("SENDER_EMAIL")
    app_password = APP_PASSWORD or os.getenv("APP_PASSWORD")

    if not sender_email or not app_password:
        raise RuntimeError("SENDER_EMAIL and APP_PASSWORD environment variables are not set.")

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            try:
                smtp.login(sender_email, app_password)
            except smtplib.SMTPAuthenticationError as e:
                raise RuntimeError(
                    "SMTP authentication failed. Ensure you are using a Gmail App Password, "
                    "not your standard login password."
                ) from e

            try:
                smtp.send_message(msg, to_addrs=recipients)
            except smtplib.SMTPRecipientsRefused as e:
                raise RuntimeError(f"All recipients were refused: {recipients}") from e
            except smtplib.SMTPException as e:
                raise RuntimeError("Failed to send email due to an SMTP error.") from e

    except smtplib.SMTPConnectError as e:
        raise RuntimeError("Could not connect to SMTP server. Check your network connection.") from e


def send_gradecard(student_email: str, student_name: str, pdf_path: str, self_send: bool = False):
    """Send a gradecard PDF to a student."""
    msg = EmailMessage()
    msg["Subject"] = f"Training Performance Report - {student_name}"
    msg["From"] = SENDER_EMAIL

    if self_send:
        msg["To"] = SENDER_EMAIL
        msg["Bcc"] = student_email
        recipients = [SENDER_EMAIL, student_email]
    else:
        msg["To"] = student_email
        recipients = [student_email]

    msg.set_content(
        f"""Dear {student_name},

Greetings from the Training Team.

Please find your latest training performance report attached to this email. 
You can download the PDF document to review your grades and assessment details.

If you have any queries regarding your report, please reach out to the training department.

Best regards,
Training & Assessment Team
"""
    )

    with open(pdf_path, "rb") as f:
        file_data = f.read()

    msg.add_attachment(
        file_data,
        maintype="application",
        subtype="pdf",
        filename=os.path.basename(pdf_path)
    )

    _send_smtp(msg, recipients)
    print(f"✅ Email Sent -> {', '.join(recipients)}")


def send_all_gradecards(df, self_send: bool = False) -> tuple[int, list[tuple[str, str]]]:
    """Send gradecards for all rows in `df`.
    
    Returns:
        A tuple of (sent_count, failed_list) where failed_list contains 
        tuples of (email, error_message).
    """
    sent = 0
    failed = []

    for _, row in df.iterrows():
        # Safely extract data
        email = str(row.get("Email", "")).strip()
        name = str(row.get("Name", "Student")).strip()

        if not email or "@" not in email:
            failed.append((email, "Invalid or missing email address."))
            continue

        # FIX: Recreate the EXACT filename generated by generate_gradecards()
        safe_name = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_") or "student"
        safe_email = email.replace("@", "_").replace(".", "_")
        pdf_file = f"{safe_name}_{safe_email}.pdf"
        pdf_path = os.path.join("gradecards", pdf_file)

        if not os.path.exists(pdf_path):
            failed.append((email, f"PDF file not found at expected path: {pdf_path}"))
            continue

        try:
            send_gradecard(email, name, pdf_path, self_send=self_send)
            sent += 1
            
            # RATE LIMIT: Pause for 1 second to prevent Gmail from blocking bulk sends
            time.sleep(1)
            
        except Exception as e:
            failed.append((email, str(e)))

    return sent, failed


def send_file_to_self(file_path: str, subject: str, body: str):
    """Send an arbitrary file to the configured sender email."""
    if not SENDER_EMAIL:
        raise RuntimeError("SENDER_EMAIL environment variable is not set.")

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = SENDER_EMAIL
    msg["To"] = SENDER_EMAIL
    msg.set_content(body)

    with open(file_path, "rb") as f:
        file_data = f.read()

    msg.add_attachment(
        file_data,
        maintype="application",
        subtype="octet-stream",
        filename=os.path.basename(file_path)
    )

    _send_smtp(msg, [SENDER_EMAIL])
    print(f"✅ Email Sent -> {SENDER_EMAIL}")